services:
  stream_api_integration_test_zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 12187:2181   
  
  stream_api_integration_test_kafka:
    image: confluentinc/cp-kafka:7.9.1
    depends_on:
      - stream_api_integration_test_zookeeper
    ports:
      - 9097:9097 
      - 9098:9098 
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: stream_api_integration_test_zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://stream_api_integration_test_kafka:9093,PLAINTEXT_HOST://localhost:9097,PLAINTEXT_UI://192.168.1.168:9098
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,PLAINTEXT_UI:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  
  stream_api_kafka_ui:   
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - stream_api_integration_test_kafka    
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 192.168.1.168:9098
      DYNAMIC_CONFIG_ENABLED: 'true' 